### ISSUE TITLE
Cannot use 'in' operator to search for '_leaflet_id' in undefined

### ISSUE THREAD

**Issue by alexhuynh7** [linghuam/TrackPlayback#37]
I tried to use this library with Leaflet map and Blazor. The playback control was shown on the map but no markers were shown.
Just got this error on console: Cannot use 'in' operator to search for '_leaflet_id' in undefined
It looks like a problem with the layer but I can't quite get it yet.

**Comment by jdegroot2797** [comment]
Looking at the same issue you're having myself as well. If you happen to understand and figure it out please share! Likewise I will do the same 😄

**Comment by alexhuynh7** [comment]
I manually checked the source code, and had to add more conditions and it worked.
Just find in leaflet.trackplayback.js: this._map.hasLayer(this._trackPointFeatureGroup)
Change it to: this._trackPointFeatureGroup&&this._map.hasLayer(this._trackPointFeatureGroup)
